spring.application.name=equipment-request-service
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/equipment_service
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none